# Generated by Django 4.2.1 on 2023-05-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userinfo_email_alter_userinfo_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='city',
            field=models.CharField(default='上海', max_length=64, verbose_name='城市'),
        ),
    ]
