# Generated by Django 4.2.1 on 2023-05-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_userinfo_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='city',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='城市'),
        ),
    ]
